### ISSUE TITLE
Pas beaucoup d'infos sur le site

### ISSUE THREAD

**Issue by MJV-collab** [betagouv/Aidants_Connect#133]
Bonjour
ça manque de FAQ non ?

**Comment by Anna-Livia** [comment]
Bonjour @MJV-collab ,
Quelle sont les questions dont vous auriez aimé trouver les réponses dans la FAQ ?

**Comment by Anna-Livia** [comment]
Nous avons ajouté une page d'explication au site : https://aidantsconnect.beta.gouv.fr/guide_utilisation/
Je ferme l'issue, n'hésitez pas à revenir vers nous si vous avez des questions supplémentaires.
