### ISSUE TITLE
[New issue] Unrequired fields when filling a user profile

### ISSUE THREAD

**Issue by thimy** [betagouv/Aidants_Connect#18]
## Scenario : Aidant fills user profile without all information

**Given** I am logged in as an Aidant
**When** I miss some information (first names, preferred name, date of birth, place of birth or country of birth
**Then** I am still able to find a user's information

**Comment by Anna-Livia** [comment]
According to @Flightan, if there is an error in `gender`, FC will correct the user info.

**Comment by Anna-Livia** [comment]
Closing as we do not ask for information anymore
