### ISSUE TITLE
Code 500 : Erreur interne du serveur

### ISSUE THREAD

**Issue by mbelloiseau** [betagouv/Aidants_Connect#384]
Bonjour,

Nous rencontrons des difficultés de connexion pour certains utilisateurs. Nous avons une instance Aidant Connect avec ~ 70 utilisateurs et certains rencontrent cette erreur à la connexion.

A priori ils sont tous créés sur le même modèle et se connectent via l'otp. Nous utilisons la dernière version du projet.

Dans les logs on peut voir ce genre de message : `aidants_connect_web.models.Aidant.DoesNotExist: Aidant matching query does not exist.`

Si quelqu'un a une piste, une idée.

Merci :+1: 

![image](https://user-images.githubusercontent.com/56693925/122225218-29c34e80-ceb5-11eb-90ac-0c2d2994e274.png)

**Comment by tut-tuuut** [comment]
Bonjour,

Désolée du retard de réponse. Nous avons rencontré un problème semblable en juillet et nous n'avons pas immédiatement fait le lien avec votre message.

Est-ce que les utilisateurs concernés ont des e-mails en majuscules en base de données ? Ou juste avec certaines lettres en majuscules ? Nous avons identifié un bug dans le module MagicAuth, où l'e-mail de l'utilisateur n'est pas totalement insensible à la casse.
Le bug se produit uniquement si l'utilisateur a un e-mail contenant des majuscules dans la base de données.

Pour contourner le problème, nous avons passé en minuscules les e-mails en base de données (champs `username` et `email` de la table aidant). Nous avons lancé une PR pour résoudre le bug, mais elle n'a pas encore été acceptée :  : https://github.com/betagouv/django-magicauth/pull/45

**Comment by mbelloiseau** [comment]
Bonjour,

Réponse -très- tardive de mon côté, désolé.

En effet, les comptes qui posent problème ne sont pas uniquement composés de minuscules.

Merci pour l'info :-)
