### ISSUE TITLE
Préciser que l'identifiant aidant est son adresse mail

### ISSUE THREAD

**Issue by Morendil** [betagouv/Aidants_Connect#81]
L'écran de connexion par login/mot de passe contient le libellé "Nom d'utilisateur", c'est trompeur car il exige en fait la saisie de l'adresse mail.

Fermer cette issue si le système d'authentficiation des aidants est remplacé par magic_auth comme prévu.

**Comment by Anna-Livia** [comment]
Transféré dans le Trello
