### ISSUE TITLE
Fournir un script d'initialisation de la base Postgres

### ISSUE THREAD

**Issue by Morendil** [betagouv/Aidants_Connect#82]
Pour faciliter la prise en main par les personnes souhaitant contribuer au développement, il peut être utile de savoir initialiser rapidement une base de données avec au minimum un aidant, permettant de se connecter comme aidant. (La possibilité de créer un aidant via l'admin de Django en fait une question de confort plus qu'un besoin critique.)

**Comment by Anna-Livia** [comment]
Transféré
